export {default as Content} from './Content';
export {default as Header} from './Header';
export {default as FrontButtons} from './FrontButtons';
export {default as Frontpage} from './Frontpage';
export {default as FrontInput} from './FrontInput';
export {default as QueryInstruction} from './QueryInstruction';
export {default as QueryQuestions} from './QueryQuestions';
export {default as QueryContent} from './QueryContent';
export {default as Querypage} from './Querypage';