export {default as Content} from './Content';
export {default as Header} from './Header';
export {default as Qcategories} from './Qcategories';
export {default as Etusivu} from './Etusivu';
export {default as Tietokentta} from './Tietokentta';
export {default as Instruction} from './Instruction';
export {default as Questions} from './Questions';
export {default as KyselyContent} from './KyselyContent';
export {default as Kyselysivu} from './Kyselysivu';
// export {default as LowerButtons} from './LowerButtons';
// export {default as TitleBar} from './TitleBar';
// export {default as TitleButton} from './TitleButton';
